export const jobList = [
  {
    id: 1,
    title: "Front-End Developer",
    company: "TechVision",
    location: "Remote",
    skills: ["HTML", "CSS", "React"],
    match: 0,
    description: "Build responsive interfaces for modern web applications.",
  },
  {
    id: 2,
    title: "Full Stack Engineer",
    company: "CodeLab",
    location: "Tirana, Albania",
    skills: ["React", "Node.js", "MongoDB"],
    match: 0,
    description:
      "Develop end-to-end web solutions with a focus on scalability.",
  },
  {
    id: 3,
    title: "UI/UX Designer",
    company: "Designify",
    location: "Remote",
    skills: ["Figma", "Adobe XD", "Prototyping"],
    match: 0,
    description: "Design intuitive user experiences and modern interfaces.",
  },
  {
    id: 4,
    title: "Back-End Developer",
    company: "DevPro",
    location: "Berlin, Germany",
    skills: ["Node.js", "Express", "SQL"],
    match: 0,
    description: "Build reliable APIs and manage database operations.",
  },
  {
    id: 5,
    title: "React Native Engineer",
    company: "AppForge",
    location: "Remote",
    skills: ["React Native", "Expo", "Firebase"],
    match: 0,
    description:
      "Create cross-platform mobile applications using React Native.",
  },
  {
    id: 6,
    title: "Data Analyst",
    company: "InsightWorks",
    location: "Prague, Czech Republic",
    skills: ["Python", "SQL", "Tableau"],
    match: 0,
    description: "Analyze large datasets to identify trends and insights.",
  },
  {
    id: 7,
    title: "Software Tester",
    company: "QATech",
    location: "Remote",
    skills: ["Cypress", "Selenium", "Manual Testing"],
    match: 0,
    description:
      "Perform QA testing to ensure product quality and performance.",
  },
  {
    id: 8,
    title: "DevOps Engineer",
    company: "CloudOps",
    location: "Paris, France",
    skills: ["Docker", "Kubernetes", "AWS"],
    match: 0,
    description:
      "Automate deployment pipelines and manage cloud infrastructure.",
  },
  {
    id: 9,
    title: "Project Manager",
    company: "AgileCore",
    location: "Remote",
    skills: ["Scrum", "Kanban", "Jira"],
    match: 0,
    description: "Lead software projects ensuring timely delivery and quality.",
  },
  {
    id: 10,
    title: "AI Research Assistant",
    company: "NeuraTech",
    location: "London, UK",
    skills: ["Python", "TensorFlow", "Machine Learning"],
    match: 0,
    description: "Assist in research and development of AI-based technologies.",
  },
  {
    id: 11,
    title: "Cybersecurity Analyst",
    company: "SecureNet",
    location: "Remote",
    skills: ["Network Security", "Firewalls", "SIEM"],
    match: 0,
    description: "Monitor and protect systems against cyber threats.",
  },
  {
    id: 12,
    title: "Database Administrator",
    company: "DataCore",
    location: "Rome, Italy",
    skills: ["MySQL", "PostgreSQL", "NoSQL"],
    match: 0,
    description: "Manage, maintain, and optimize database performance.",
  },
  {
    id: 13,
    title: "Graphic Designer",
    company: "Pixely",
    location: "Remote",
    skills: ["Photoshop", "Illustrator", "Canva"],
    match: 0,
    description: "Design visuals and graphics for digital and print media.",
  },
  {
    id: 14,
    title: "SEO Specialist",
    company: "Rankify",
    location: "Remote",
    skills: ["SEO", "Google Analytics", "Content Strategy"],
    match: 0,
    description:
      "Optimize websites to increase visibility and search rankings.",
  },
  {
    id: 15,
    title: "Cloud Engineer",
    company: "SkyCloud",
    location: "Berlin, Germany",
    skills: ["AWS", "Azure", "Terraform"],
    match: 0,
    description: "Deploy and manage scalable applications on the cloud.",
  },
  {
    id: 16,
    title: "Business Analyst",
    company: "DataBridge",
    location: "Tirana, Albania",
    skills: ["Excel", "Power BI", "SQL"],
    match: 0,
    description: "Analyze business data and deliver actionable insights.",
  },
  {
    id: 17,
    title: "Software Architect",
    company: "Structura",
    location: "Remote",
    skills: ["Microservices", "System Design", "AWS"],
    match: 0,
    description: "Design scalable software architectures and system workflows.",
  },
  {
    id: 18,
    title: "Mobile App Developer",
    company: "Appify",
    location: "New York, USA",
    skills: ["Swift", "Kotlin", "React Native"],
    match: 0,
    description: "Develop and maintain iOS and Android mobile apps.",
  },
  {
    id: 19,
    title: "Content Writer",
    company: "WordFlow",
    location: "Remote",
    skills: ["Copywriting", "SEO", "Editing"],
    match: 0,
    description: "Create engaging blog posts and digital marketing content.",
  },
  {
    id: 20,
    title: "System Administrator",
    company: "TechServe",
    location: "Dublin, Ireland",
    skills: ["Linux", "Windows Server", "Networking"],
    match: 0,
    description: "Maintain IT infrastructure and ensure network uptime.",
  },
  {
    id: 21,
    title: "Network Engineer",
    company: "NetWave",
    location: "Warsaw, Poland",
    skills: ["Cisco", "VPN", "Routing"],
    match: 0,
    description: "Configure and maintain secure and efficient network systems.",
  },
  {
    id: 22,
    title: "Technical Support Specialist",
    company: "HelpDesk Co.",
    location: "Remote",
    skills: ["Customer Support", "Troubleshooting", "Windows"],
    match: 0,
    description:
      "Assist users in resolving technical software and hardware issues.",
  },
  {
    id: 23,
    title: "Product Manager",
    company: "Innovatek",
    location: "Remote",
    skills: ["Agile", "Roadmaps", "User Research"],
    match: 0,
    description:
      "Oversee the product lifecycle and ensure alignment with business goals.",
  },
  {
    id: 24,
    title: "Data Engineer",
    company: "Datastream",
    location: "Vienna, Austria",
    skills: ["Python", "ETL", "BigQuery"],
    match: 0,
    description:
      "Develop and maintain data pipelines and integration workflows.",
  },
  {
    id: 25,
    title: "Game Developer",
    company: "Playverse",
    location: "Remote",
    skills: ["Unity", "C#", "3D Modeling"],
    match: 0,
    description:
      "Design and code gameplay systems for interactive experiences.",
  },
  {
    id: 26,
    title: "AI Prompt Engineer",
    company: "ThinkAI",
    location: "Remote",
    skills: ["LLMs", "Python", "Prompt Design"],
    match: 0,
    description:
      "Develop and refine prompts for large language model performance.",
  },
  {
    id: 27,
    title: "Backend API Developer",
    company: "APILabs",
    location: "Madrid, Spain",
    skills: ["Node.js", "Express", "REST API"],
    match: 0,
    description: "Create and optimize secure and efficient backend APIs.",
  },
  {
    id: 28,
    title: "Web Designer",
    company: "CreativeFlow",
    location: "Remote",
    skills: ["HTML", "CSS", "UI Design"],
    match: 0,
    description: "Design modern and responsive websites for various clients.",
  },
  {
    id: 29,
    title: "System Analyst",
    company: "LogicNet",
    location: "Belgrade, Serbia",
    skills: ["Business Analysis", "Requirements", "Modeling"],
    match: 0,
    description:
      "Analyze and optimize information systems for enterprise clients.",
  },
  {
    id: 30,
    title: "Blockchain Developer",
    company: "ChainWorks",
    location: "Zurich, Switzerland",
    skills: ["Solidity", "Ethereum", "Smart Contracts"],
    match: 0,
    description: "Develop decentralized applications and blockchain solutions.",
  },
  {
    id: 31,
    title: "Python Developer",
    company: "CodeVerse",
    location: "Remote",
    skills: ["Python", "Django", "Flask"],
    match: 0,
    description: "Build backend systems and APIs using Python frameworks.",
  },
  {
    id: 32,
    title: "Marketing Specialist",
    company: "AdPulse",
    location: "Rome, Italy",
    skills: ["Social Media", "Ads", "Email Marketing"],
    match: 0,
    description: "Plan and execute digital marketing campaigns.",
  },
  {
    id: 33,
    title: "Quality Assurance Lead",
    company: "Testify",
    location: "Remote",
    skills: ["Automation", "Jest", "Manual Testing"],
    match: 0,
    description: "Supervise testing processes to maintain product reliability.",
  },
  {
    id: 34,
    title: "Embedded Systems Engineer",
    company: "MicroLogic",
    location: "Munich, Germany",
    skills: ["C", "C++", "Microcontrollers"],
    match: 0,
    description: "Develop and debug firmware for embedded electronic systems.",
  },
  {
    id: 35,
    title: "Game Artist",
    company: "PixelForge",
    location: "Remote",
    skills: ["3D Modeling", "Blender", "Concept Art"],
    match: 0,
    description: "Create 2D and 3D visual assets for video games.",
  },
  {
    id: 36,
    title: "HR Software Coordinator",
    company: "PeopleTech",
    location: "Remote",
    skills: ["HR Tools", "Onboarding", "Analytics"],
    match: 0,
    description: "Manage digital HR systems and support recruitment workflows.",
  },
  {
    id: 37,
    title: "Technical Writer",
    company: "DocuFlow",
    location: "Remote",
    skills: ["Documentation", "Markdown", "APIs"],
    match: 0,
    description:
      "Write and maintain clear and precise technical documentation.",
  },
  {
    id: 38,
    title: "Sales Engineer",
    company: "SellSmart",
    location: "Budapest, Hungary",
    skills: ["Sales", "Technical Knowledge", "CRM"],
    match: 0,
    description:
      "Bridge the gap between client needs and product capabilities.",
  },
  {
    id: 39,
    title: "Cloud Security Engineer",
    company: "SafeCloud",
    location: "Remote",
    skills: ["AWS", "Security", "IAM"],
    match: 0,
    description: "Implement and monitor security policies for cloud systems.",
  },
  {
    id: 40,
    title: "Research Assistant",
    company: "InnovaLab",
    location: "Cambridge, UK",
    skills: ["Python", "Data Analysis", "Research"],
    match: 0,
    description:
      "Assist in data collection and analysis for research projects.",
  },
  {
    id: 41,
    title: "Data Scientist",
    company: "AIlytics",
    location: "Remote",
    skills: ["Python", "Pandas", "Machine Learning"],
    match: 0,
    description:
      "Build predictive models and extract insights from large datasets.",
  },
  {
    id: 42,
    title: "Video Editor",
    company: "MediaForge",
    location: "Remote",
    skills: ["Premiere Pro", "After Effects", "DaVinci Resolve"],
    match: 0,
    description:
      "Edit and produce professional-quality video content for campaigns.",
  },
  {
    id: 43,
    title: "Financial Analyst",
    company: "FinScope",
    location: "London, UK",
    skills: ["Excel", "Financial Modeling", "Power BI"],
    match: 0,
    description: "Analyze financial data to guide business decision-making.",
  },
  {
    id: 44,
    title: "IT Support Engineer",
    company: "SysAid",
    location: "Remote",
    skills: ["Windows", "Networking", "Helpdesk"],
    match: 0,
    description: "Provide hardware and software support to clients and teams.",
  },
  {
    id: 45,
    title: "Front-End Angular Developer",
    company: "WebCraft",
    location: "Tirana, Albania",
    skills: ["Angular", "TypeScript", "SCSS"],
    match: 0,
    description: "Develop dynamic front-end interfaces with Angular framework.",
  },
  {
    id: 46,
    title: "AI Engineer",
    company: "CognitiveLabs",
    location: "Zurich, Switzerland",
    skills: ["Python", "PyTorch", "Deep Learning"],
    match: 0,
    description:
      "Design and implement AI solutions using deep learning frameworks.",
  },
  {
    id: 47,
    title: "Product Designer",
    company: "UXify",
    location: "Remote",
    skills: ["UI Design", "Figma", "Prototyping"],
    match: 0,
    description:
      "Create user-centered designs for digital products and experiences.",
  },
  {
    id: 48,
    title: "Software Intern",
    company: "CodeStarter",
    location: "Remote",
    skills: ["HTML", "CSS", "JavaScript"],
    match: 0,
    description: "Assist development teams with frontend tasks and testing.",
  },
  {
    id: 49,
    title: "IT Project Coordinator",
    company: "SoftFlow",
    location: "Skopje, North Macedonia",
    skills: ["Project Management", "Scheduling", "Reporting"],
    match: 0,
    description: "Coordinate software project activities and documentation.",
  },
  {
    id: 50,
    title: "Penetration Tester",
    company: "HackShield",
    location: "Remote",
    skills: ["Kali Linux", "PenTesting", "OWASP"],
    match: 0,
    description:
      "Identify and exploit vulnerabilities in software and networks.",
  },
  {
    id: 51,
    title: "Network Security Specialist",
    company: "SecurePath",
    location: "Berlin, Germany",
    skills: ["Firewalls", "IDS/IPS", "Network Monitoring"],
    match: 0,
    description: "Protect organizational networks from unauthorized access.",
  },
  {
    id: 52,
    title: "Cloud Solutions Architect",
    company: "CloudSync",
    location: "Remote",
    skills: ["AWS", "Kubernetes", "DevOps"],
    match: 0,
    description:
      "Architect cloud-based solutions with reliability and scalability.",
  },
  {
    id: 53,
    title: "Game Tester",
    company: "PixelPlay",
    location: "Remote",
    skills: ["Testing", "Bug Tracking", "Gameplay Analysis"],
    match: 0,
    description: "Playtest and report gameplay issues in new game releases.",
  },
  {
    id: 54,
    title: "Operations Analyst",
    company: "ProcessIQ",
    location: "Athens, Greece",
    skills: ["Data Analytics", "Excel", "Process Mapping"],
    match: 0,
    description: "Evaluate operational processes and recommend improvements.",
  },
  {
    id: 55,
    title: "Customer Success Manager",
    company: "ClientCore",
    location: "Remote",
    skills: ["CRM", "Customer Support", "Communication"],
    match: 0,
    description: "Build strong relationships and ensure client satisfaction.",
  },
  {
    id: 56,
    title: "Software Maintenance Engineer",
    company: "FixIT",
    location: "Milan, Italy",
    skills: ["Bug Fixing", "Debugging", "Version Control"],
    match: 0,
    description: "Maintain and troubleshoot existing software applications.",
  },
  {
    id: 57,
    title: "Game Sound Designer",
    company: "SoundForge",
    location: "Remote",
    skills: ["Sound Design", "Audio Mixing", "Game Audio"],
    match: 0,
    description:
      "Create immersive sound effects and background music for games.",
  },
  {
    id: 58,
    title: "AI Data Trainer",
    company: "ModelTrain",
    location: "Remote",
    skills: ["Data Labeling", "Prompt Engineering", "Python"],
    match: 0,
    description: "Curate and annotate datasets for machine learning models.",
  },
  {
    id: 59,
    title: "E-Commerce Manager",
    company: "ShopLink",
    location: "London, UK",
    skills: ["Shopify", "SEO", "Digital Ads"],
    match: 0,
    description:
      "Oversee online sales platforms and optimize marketing funnels.",
  },
  {
    id: 60,
    title: "Full Stack Intern",
    company: "WebEdge",
    location: "Remote",
    skills: ["React", "Node.js", "MongoDB"],
    match: 0,
    description:
      "Work with developers to build and test full stack applications.",
  },
  {
    id: 61,
    title: "Junior Web Developer",
    company: "WebStart",
    location: "Remote",
    skills: ["HTML", "CSS", "JavaScript"],
    match: 0,
    description:
      "Support the web development team with front-end tasks and updates.",
  },
  {
    id: 62,
    title: "React Developer",
    company: "NextGen Apps",
    location: "Lisbon, Portugal",
    skills: ["React", "Redux", "JavaScript"],
    match: 0,
    description: "Develop and maintain modern single-page web applications.",
  },
  {
    id: 63,
    title: "IT Consultant",
    company: "ConsultPro",
    location: "Remote",
    skills: ["IT Strategy", "Analysis", "Systems Integration"],
    match: 0,
    description: "Advise clients on IT improvements and technology solutions.",
  },
  {
    id: 64,
    title: "Game Programmer",
    company: "PixelCraft",
    location: "Warsaw, Poland",
    skills: ["Unity", "C#", "Game Logic"],
    match: 0,
    description:
      "Implement gameplay systems and tools for video game development.",
  },
  {
    id: 65,
    title: "Backend Developer (Python)",
    company: "DevAxis",
    location: "Remote",
    skills: ["Python", "Flask", "APIs"],
    match: 0,
    description: "Create and manage REST APIs and server-side logic.",
  },
  {
    id: 66,
    title: "UI Engineer",
    company: "UXVision",
    location: "Remote",
    skills: ["React", "Tailwind CSS", "UI Testing"],
    match: 0,
    description:
      "Design and develop user interface components and interactions.",
  },
  {
    id: 67,
    title: "Network Administrator",
    company: "NetSecure",
    location: "Amsterdam, Netherlands",
    skills: ["Cisco", "Routing", "Firewalls"],
    match: 0,
    description: "Monitor and maintain computer networks for smooth operation.",
  },
  {
    id: 68,
    title: "ML Ops Engineer",
    company: "DeepOps",
    location: "Remote",
    skills: ["MLflow", "AWS", "Docker"],
    match: 0,
    description:
      "Deploy and maintain machine learning pipelines and infrastructure.",
  },
  {
    id: 69,
    title: "AI Chatbot Developer",
    company: "BotHive",
    location: "Remote",
    skills: ["Python", "Dialogflow", "APIs"],
    match: 0,
    description: "Design and integrate chatbots for customer engagement.",
  },
  {
    id: 70,
    title: "Web Project Manager",
    company: "SiteFlow",
    location: "Prague, Czech Republic",
    skills: ["Agile", "Jira", "Communication"],
    match: 0,
    description:
      "Coordinate design and development teams for website projects.",
  },
  {
    id: 71,
    title: "Automation Engineer",
    company: "AutoSys",
    location: "Milan, Italy",
    skills: ["Python", "CI/CD", "Testing"],
    match: 0,
    description: "Develop and maintain automation frameworks and test suites.",
  },
  {
    id: 72,
    title: "Junior Data Scientist",
    company: "DataSpring",
    location: "Remote",
    skills: ["Python", "Pandas", "Machine Learning"],
    match: 0,
    description:
      "Support data science projects and perform exploratory analysis.",
  },
  {
    id: 73,
    title: "Full Stack Developer",
    company: "DevLink",
    location: "Remote",
    skills: ["React", "Node.js", "SQL"],
    match: 0,
    description:
      "Work on both frontend and backend development of web applications.",
  },
  {
    id: 74,
    title: "Digital Marketer",
    company: "AdSphere",
    location: "Remote",
    skills: ["Google Ads", "Analytics", "SEO"],
    match: 0,
    description:
      "Plan and execute digital campaigns to increase traffic and conversions.",
  },
  {
    id: 75,
    title: "Mobile App Tester",
    company: "AppCheck",
    location: "Remote",
    skills: ["Testing", "QA", "Bug Reporting"],
    match: 0,
    description:
      "Test mobile applications for usability and performance issues.",
  },
  {
    id: 76,
    title: "Content Strategist",
    company: "WordBridge",
    location: "Remote",
    skills: ["SEO", "Content Planning", "Copywriting"],
    match: 0,
    description: "Develop content strategies to boost engagement and reach.",
  },
  {
    id: 77,
    title: "Hardware Engineer",
    company: "TechBuild",
    location: "Berlin, Germany",
    skills: ["PCB Design", "Electronics", "C"],
    match: 0,
    description: "Design and test hardware components and embedded systems.",
  },
  {
    id: 78,
    title: "SaaS Product Owner",
    company: "CloudSuite",
    location: "Remote",
    skills: ["Product Management", "Agile", "Scrum"],
    match: 0,
    description: "Define features and manage roadmap for SaaS applications.",
  },
  {
    id: 79,
    title: "PHP Developer",
    company: "WebHub",
    location: "Remote",
    skills: ["PHP", "Laravel", "MySQL"],
    match: 0,
    description: "Develop and maintain backend systems using PHP and Laravel.",
  },
  {
    id: 80,
    title: "Robotics Engineer",
    company: "RoboLabs",
    location: "Munich, Germany",
    skills: ["ROS", "Python", "Automation"],
    match: 0,
    description: "Design and program robotic systems for industrial use.",
  },
  {
    id: 81,
    title: "Web Accessibility Specialist",
    company: "InclusiveWeb",
    location: "Remote",
    skills: ["WCAG", "HTML", "Accessibility Testing"],
    match: 0,
    description:
      "Ensure web applications meet accessibility and usability standards.",
  },
  {
    id: 82,
    title: "Database Developer",
    company: "DataForge",
    location: "Remote",
    skills: ["SQL", "PostgreSQL", "Stored Procedures"],
    match: 0,
    description:
      "Design and implement optimized database solutions for web systems.",
  },
  {
    id: 83,
    title: "Game Level Designer",
    company: "PlayLogic",
    location: "Remote",
    skills: ["Unity", "Level Design", "Scripting"],
    match: 0,
    description:
      "Design interactive and balanced game levels for user engagement.",
  },
  {
    id: 84,
    title: "React Frontend Intern",
    company: "DevTrain",
    location: "Remote",
    skills: ["React", "HTML", "CSS"],
    match: 0,
    description: "Assist in frontend feature development using React.js.",
  },
  {
    id: 85,
    title: "Digital Illustrator",
    company: "ArtForge",
    location: "Remote",
    skills: ["Illustrator", "Photoshop", "Digital Art"],
    match: 0,
    description: "Create illustrations and design assets for branding and web.",
  },
  {
    id: 86,
    title: "Network Technician",
    company: "LinkNet",
    location: "Lisbon, Portugal",
    skills: ["Networking", "Cabling", "Diagnostics"],
    match: 0,
    description: "Support installation and maintenance of network systems.",
  },
  {
    id: 87,
    title: "Software QA Tester",
    company: "SoftCheck",
    location: "Remote",
    skills: ["Manual Testing", "Automation", "JIRA"],
    match: 0,
    description:
      "Test software applications to ensure stability and functionality.",
  },
  {
    id: 88,
    title: "E-Learning Developer",
    company: "EduTech",
    location: "Remote",
    skills: ["Storyline", "HTML", "Multimedia"],
    match: 0,
    description: "Design and build interactive online learning content.",
  },
  {
    id: 89,
    title: "Research Data Analyst",
    company: "InsightLab",
    location: "Vienna, Austria",
    skills: ["R", "Python", "Statistics"],
    match: 0,
    description: "Analyze research data to identify patterns and insights.",
  },
  {
    id: 90,
    title: "Web Content Manager",
    company: "WebPro",
    location: "Remote",
    skills: ["CMS", "SEO", "Copy Editing"],
    match: 0,
    description:
      "Manage and optimize website content and publication schedules.",
  },
  {
    id: 91,
    title: "IT Systems Engineer",
    company: "InfraTech",
    location: "Berlin, Germany",
    skills: ["Linux", "Scripting", "Cloud Systems"],
    match: 0,
    description: "Design and maintain scalable and secure IT infrastructure.",
  },
  {
    id: 92,
    title: "Backend Go Developer",
    company: "GoCore",
    location: "Remote",
    skills: ["GoLang", "APIs", "SQL"],
    match: 0,
    description: "Develop high-performance backend services using Go.",
  },
  {
    id: 93,
    title: "Cloud Data Engineer",
    company: "DataSky",
    location: "Remote",
    skills: ["BigQuery", "Python", "ETL"],
    match: 0,
    description: "Build and optimize data pipelines in cloud environments.",
  },
  {
    id: 94,
    title: "Web Analytics Specialist",
    company: "Insightify",
    location: "Remote",
    skills: ["Google Analytics", "Data Studio", "SEO"],
    match: 0,
    description:
      "Analyze website traffic and report on key performance metrics.",
  },
  {
    id: 95,
    title: "AI Product Developer",
    company: "NeuralEdge",
    location: "Remote",
    skills: ["Python", "APIs", "LLMs"],
    match: 0,
    description: "Integrate AI capabilities into real-world digital products.",
  },
  {
    id: 96,
    title: "Web Developer Intern",
    company: "DevGrow",
    location: "Remote",
    skills: ["HTML", "CSS", "JavaScript"],
    match: 0,
    description:
      "Assist senior developers with front-end coding and testing tasks.",
  },
  {
    id: 97,
    title: "AI Prompt Curator",
    company: "Promptly",
    location: "Remote",
    skills: ["AI Tools", "Prompt Design", "Python"],
    match: 0,
    description:
      "Refine and test AI prompts for natural language applications.",
  },
  {
    id: 98,
    title: "CRM Administrator",
    company: "ClientLink",
    location: "Remote",
    skills: ["Salesforce", "HubSpot", "Reporting"],
    match: 0,
    description: "Configure and maintain CRM systems for business operations.",
  },
  {
    id: 99,
    title: "AR/VR Developer",
    company: "VirtualForge",
    location: "Remote",
    skills: ["Unity", "C#", "3D Interaction"],
    match: 0,
    description: "Create immersive AR/VR applications for commercial clients.",
  },
  {
    id: 100,
    title: "IT Operations Assistant",
    company: "TechAssist",
    location: "Remote",
    skills: ["Support", "Monitoring", "Documentation"],
    match: 0,
    description:
      "Assist the IT operations team in daily support and maintenance tasks.",
  },
];
